### ISSUE TITLE
Flag to clean up images

### ISSUE THREAD

**Issue by SamVerschueren** [vdemedes/trevor#10]
Should we clean up images after they ran?

```sh
docker rmi $(docker images | grep '^test-pkgName-0.10.0' | awk '{ print $1; }')
```

**Comment by vdemedes** [comment]
Hmm, not sure about this one yet. Sometimes it's helpful to dive into images, that have failing tests to investigate. This helped me quite a few times.

**Comment by SamVerschueren** [comment]
Yes you're probably right. It's possible to add a flag that will keep/remove images after the tests. Or only keep at failure. Some things to think about :).

**Comment by vdemedes** [comment]
Good suggestion, I'll leave this as a feature request ;)

**Comment by vdemedes** [comment]
Ok, I think I will have to do the opposite, clean up images by default and leave them if some flag is set. I don't know if it's my fault or trevor's, but my server just ran out of space :D

**Comment by SamVerschueren** [comment]
Hahaha :D. Would be a very nice addition!
