### ISSUE TITLE
Should we use meow?

### ISSUE THREAD

**Issue by SamVerschueren** [vdemedes/trevor#13]
Maybe it's easier to use [meow](https://github.com/sindresorhus/meow) for help and  argument parsing.

**Comment by vdemedes** [comment]
Yeah, thought of it too, will probably switch in a few commits. Refactoring the whole thing now.

**Comment by vdemedes** [comment]
`meow` is now used in `master` branch.

**Comment by SamVerschueren** [comment]
Awesome!
