### ISSUE TITLE
Show decent error if no .travis.yml file was found

### ISSUE THREAD

**Issue by SamVerschueren** [vdemedes/trevor#17]
Maybe something more user-friendly then

```
Error: ENOENT: no such file or directory, open '/Users/sam/Projects/playground/trevor-test/.travis.yml'
    at Error (native)
```

**Comment by vdemedes** [comment]
Those are much better, I suppose :)

<img width="443" alt="screen shot 2015-10-22 at 9 57 14 pm" src="https://cloud.githubusercontent.com/assets/697676/10676644/e9fec706-7907-11e5-9b81-1303d6619a1a.png">

<img width="425" alt="screen shot 2015-10-22 at 9 57 41 pm" src="https://cloud.githubusercontent.com/assets/697676/10676652/f55851f8-7907-11e5-8df2-5dd582500fc0.png">

**Comment by SamVerschueren** [comment]
Very nice!
