### ISSUE TITLE
Trevor does't execute preinstall/install/postinstall scripts from package.json

### ISSUE THREAD

**Issue by vcernomschi** [vdemedes/trevor#32]
Trevor does't execute preinstall/install/postinstall scripts from package.json

Steps to reproduce:
1. Add install script to package.json.
2. Run `trevor` from Docker QuickStart Terminal

Expected result: Install script from package.json was executed.
Actual result: Install script from package.json was not executed. So no custom installation logic can be used.

**Comment by vdemedes** [comment]
Trevor has nothing to do with `npm install`, as it uses official `node` Docker images.
