### ISSUE TITLE
trevor trys to pull wrong repos

### ISSUE THREAD

**Issue by frank-dspeed** [vdemedes/trevor#34]
trevor --no-clean

   ✖  v4:  error
   ✖  v5:  error
   ✖  v6:  error

   ✖  node vv6:
Pulling repository docker.io/library/node
Tag v6-onbuild not found in repository docker.io/library/node

   ✖  node vv4:
Pulling repository docker.io/library/node

**Comment by vdemedes** [comment]
Could you post your `.travis.yml`?

**Comment by frank-dspeed** [comment]
vdemedes i corrected it already i did a complet fork of this you can watch the pull request maybe

**Comment by frank-dspeed** [comment]
you can close this issu i saw this is in early stage i will develop my own version of this but the idea is realy realy great like it much respect !
