### ISSUE TITLE
Unlink error

### ISSUE THREAD

**Issue by SamVerschueren** [vdemedes/trevor#7]
Sometimes an error occurs before the `.dockerfile` is created, for instance if the user tries to pull an unknown NodeJS version. It will try to unlink the `.dockerfile` but it rejects the unlink promise at line [86](https://github.com/vdemedes/trevor/blob/master/index.js#L86). Because the rejection is not catched, it will not go to last `then` function here https://github.com/vdemedes/trevor/blob/master/index.js#L89-L98.

A solution would be to just catch the error and do nothing with it or first check if the file exists.

```js
return fs.unlink(tmpPath)
  .catch(function (err) {
    // do nothing
  });
```

**Comment by vdemedes** [comment]
Thank you for pointing this out ;)
